kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.repoName }}
  labels:
    app: ${{ values.repoName }}
    argocd/app-name: ${{ values.repoName }}
    argocd/app-selector: ${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.repoName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
        app.kubernetes.io/component: backstage
        backstage.io/kubernetes-id: ${{ values.namespace }}
        argocd.argoproj.io/instance: ${{ values.repoName }}
        argocd/app-name: ${{ values.repoName }}
        argocd/app-selector: ${{ values.repoName }}
    spec:
      containers:
        - name: ${{ values.repoName }}
          image: ${{ values.imageRepository }}/${{ values.imageUrl }}/${{ values.repoName }}:latest
          ports:
            - name: http-${{ values.port }}
              containerPort: ${{ values.port }}
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
            requests:
              cpu: "250m"
              memory: "256Mi"
