kind: Service
apiVersion: v1
metadata:
  name: ${{ values.repoName }}
  labels:
    app: ${{ values.repoName }}
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: ${{ values.namespace }}
    argocd.argoproj.io/instance: ${{ values.repoName }}
    argocd/app-name: ${{ values.repoName }}
    argocd/app-selector: ${{ values.repoName }}
spec:
  ports:
    - name: http-${{ values.port }}
      port: ${{ values.port }}
      protocol: TCP
      targetPort: ${{ values.port }}
  selector:
    app: ${{ values.repoName }}
