apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ${{ values.repoName }}-el
  namespace: ${{ values.namespace }}
  labels:
    janus-idp.io/tekton: ${{ values.repoName }}
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-pull-request
      interceptors:
        - params:
            - name: eventTypes
              value: ['pull_request']
          ref:
            name: github
        - params:
            - name: git-revision
              value: >-
                (body.ref.contains('main'))
            - name: overlays
              value: null
          ref:
            name: cel
      template:
        ref: ${{ values.repoName }}-run-pipeline
